services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investidor_app
    networks:
      - investidor_network
    depends_on:
      - db
    user: "1000:1000"
    volumes:
      - ./investidor_app:/var/www
    ports:
    - "8000:8000"
     environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=investidor
      - DB_USERNAME=investidor
      - DB_PASSWORD=investidor

  db:
    image: mysql:8.0
    container_name: mysql_db
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: investidor
      MYSQL_USER: investidor
      MYSQL_PASSWORD: investidor
      MYSQL_ROOT_PASSWORD: root
    networks:
      - investidor_network
    ports:
      - "3306:3306"

networks:
  investidor_network:
    driver: bridge

volumes:
  mysqldata:
