services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investidor_app
    networks:
      - investidor10_investidor_network
    depends_on:
      - db
    restart: always
    user: "1000:1000"
    volumes:
      - ./investidor_app:/var/www
    ports:
    - "8080:8000"
    environment:
     DB_HOST: db
     DB_PORT: 3306
     DB_DATABASE: investidor
     DB_USER: investidor
     DB_PASSWORD: investidor
     DB_USERNAME_ROOT: root
     DB_PASSWORD_ROOT: root

  web:
    image: nginx:latest
    container_name: investidor_nginx
    depends_on:
      - app
    networks:
      - investidor10_investidor_network
    ports:
      - "8000:80"
    volumes:
      - ./investidor_app/news:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mysql:8.0
    container_name: mysql_db
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: investidor
      MYSQL_USER: investidor
      MYSQL_PASSWORD: investidor
      MYSQL_ROOT_PASSWORD: root
    networks:
      - investidor10_investidor_network
    ports:
      - "3306:3306"

networks:
  investidor10_investidor_network:
    driver: bridge

volumes:
  mysqldata:
